apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-db
  namespace: joplin-server-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-db
  template:
    metadata:
      labels:
        app: joplin-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: joplin-db-data
              mountPath: /var/lib/postgresql/data
          envFrom:
          - configMapRef:
              name: joplin-db-config
      volumes:
        - name: joplin-db-data
          persistentVolumeClaim:
            claimName: joplin-db-pvc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: joplin-app
  namespace: joplin-server-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joplin-app
  template:
    metadata:
      labels:
        app: joplin-app
    spec:
      containers:
        - name: joplin-server
          image: etechonomy/joplin-server:latest
          ports:
            - containerPort: 22300
          envFrom:
          - configMapRef:
              name: joplin-app-config
